// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseCharts: typeof import('./src/components/BaseCharts.vue')['default']
    BaseForm: typeof import('./src/components/BaseForm.vue')['default']
    BaseTable: typeof import('./src/components/BaseTable.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    ElButton: typeof import('element-plus/es/el-button')['default']
    ElDatePicker: typeof import('element-plus/es/el-date-picker')['default']
    ElDescriptions: typeof import('element-plus/es/el-descriptions')['default']
    ElDescriptionsItem: typeof import('element-plus/es/el-descriptions-item')['default']
    ElDialog: typeof import('element-plus/es/el-dialog')['default']
    ElDropdown: typeof import('element-plus/es/el-dropdown')['default']
    ElDropdownItem: typeof import('element-plus/es/el-dropdown-item')['default']
    ElDropdownMenu: typeof import('element-plus/es/el-dropdown-menu')['default']
    ElForm: typeof import('element-plus/es/el-form')['default']
    ElFormItem: typeof import('element-plus/es/el-form-item')['default']
    ElImage: typeof import('element-plus/es/el-image')['default']
    ElInput: typeof import('element-plus/es/el-input')['default']
    ElMenu: typeof import('element-plus/es/el-menu')['default']
    ElMenuItem: typeof import('element-plus/es/el-menu-item')['default']
    ElOption: typeof import('element-plus/es/el-option')['default']
    ElPagination: typeof import('element-plus/es/el-pagination')['default']
    ElProgress: typeof import('element-plus/es/el-progress')['default']
    ElSelect: typeof import('element-plus/es/el-select')['default']
    ElSubmenu: typeof import('element-plus/es/el-submenu')['default']
    ElSwitch: typeof import('element-plus/es/el-switch')['default']
    ElTable: typeof import('element-plus/es/el-table')['default']
    ElTableColumn: typeof import('element-plus/es/el-table-column')['default']
    ElTag: typeof import('element-plus/es/el-tag')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    I18n: typeof import('./src/components/I18n.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Tabs: typeof import('./src/components/Tabs.vue')['default']
    Tags: typeof import('./src/components/Tags.vue')['default']
    Upload: typeof import('./src/components/Upload.vue')['default']
  }
}

export {}
